python translate.py -gpu 0 \
                    -batch_size 20 \
                    -beam_size 10 \
                    -model ~/ProjectModels/knowledgeComprehension/model_step_18000.pt \
                    -src ~/ProjectData/seq2seq/valid-src \
                    -output predict.out \
                    -min_length 35 \
                    -verbose \
                    -stepwise_penalty \
                    -coverage_penalty summary \
                    -beta 5 \
                    -length_penalty wu \
                    -alpha 0.9 \
                    -verbose \
                    -block_ngram_repeat 3 \
